### PR TITLE
Dockerize contextualise

### LINKED ISSUE #2: Any plans to Dockerize contextualise?
This might help with users' system dependencies and get them up-and-running quicker.

/cc @ibnesayeed

### PR DESCRIPTION
**Pull request by machawk1**
Adds a Dockerfile and some instructions to the README for running contextualise using Docker.

Closes #2 

ping @brettkromkamp

### CODE REVIEW

**Comment by ibnesayeed** [comment]
Is it actually working? I doubt it because you have installed PG in the same image, but your CMD does not boot the database (unless it is booted and initialized by the python code on application invocation). It would be better to run the app and DB as micro-services in separate containers and provide and compose file.

**Comment by brettkromkamp** [comment]
@ibnesayeed Although what you are saying probably makes sense, I currently don’t have sufficient knowledge of Docker to do what you suggest.

**Comment by ibnesayeed** [comment]
Well, this would be a perfect opportunity for shameless self-advertisement of an interactive tutorial I have created that is available on the official platform of Docker training called [Application Containerization and Microservice Orchestration](https://training.play-with-docker.com/microservice-orchestration/).

**Comment by brettkromkamp** [comment]
@ibnesayeed I’ll check out your tutorial.

**Comment by machawk1** [comment]
@brettkromkamp (& @ibnesayeed), this Dockerfile is a start and very far from perfect. The intention here was to provide a basis. I figured having a basis and providing _a_ way to do it would facilitate @ibnesayeed chiming in. ;)

Separate containers as micro-services would be a good way to go. I could not get it to work on my macOS system, so simply the act of Dockerization helped alleviate dependency problems.

Thanks for the merge, @brettkromkamp! I (we) can keep working on it to make it better.

**Comment by nomatica** [comment]
@ machawk1 Thank you.  Nice to see this as a possible option. I'm not the most tech savvy of github people- in fact I'm just beginning. While I do not have a lot of experience with docker, I have played around with the cloudron insulation which ease of use has opened my eyes to the possibility.

**Pull request merged**
